version: '3.8'
services:
  db_postgres:
    image: postgres:12.9-alpine
    # restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=kevin1234
    ports:
      - '5432:5432'
    volumes:
      - '../postgres/:/var/lib/postgresql/data'

  aplicacion:
    image: pruebapython
    ports:
      - '5000:5000'
    volumes:
      - './miPrueba:/aplicacion'