# Generated by Django 4.1.2 on 2022-10-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0002_pendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='consecutivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Inventarios.pendientes'),
        ),
    ]
