# Generated by Django 4.1.2 on 2022-10-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0003_inventario_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
