# Generated by Django 4.1.2 on 2022-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0004_alter_pendientes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
