# Generated by Django 4.1.2 on 2022-10-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0005_alter_pendientes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='procesado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
